#
# Author: a0b013g - Supply Chain Architcture @WalmartLabs
#

version: '2'

services:

  ca.mc-us.vaccination.org:
    container_name: ca.mc-us.vaccination.org
    image: hyperledger/fabric-ca:x86_64-1.0.3
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mc-us.vaccination.org-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6fcc0cc98a11be4287dfbc3cc3130b4d59b89ae3fa7b0bffeef9f8787ebab104_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mc-us.vaccination.org-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6fcc0cc98a11be4287dfbc3cc3130b4d59b89ae3fa7b0bffeef9f8787ebab104_sk
#    ports:
#      - 11054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../artifacts/crypto-config/peerOrganizations/mc-us.vaccination.org/ca/:/etc/hyperledger/fabric-ca-server-config
      - ../artifacts/fabric-ca-server-config-mc-us.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml

  #Added for CouchDB
  peerdb.mc-us.vaccination.org:
    container_name: peerdb.mc-us.vaccination.org
    image: hyperledger/fabric-couchdb:x86_64-1.0.0

  peer0.mc-us.vaccination.org:
    container_name: peer0.mc-us.vaccination.org
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mc-us.vaccination.org
      - CORE_PEER_LOCALMSPID=mc-usMSP
      - CORE_PEER_ADDRESS=peer0.mc-us.vaccination.org:7051
       # Added for CouchDB as State DB
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peerdb.mc-us.vaccination.org:5984
    ports:
      - 11051:7051
      - 11053:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/mc-us.vaccination.org/peers/peer0.mc-us.vaccination.org/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.mc-us.vaccination.org
      - peerdb.mc-us.vaccination.org
    

  peer1.mc-us.vaccination.org:
    container_name: peer1.mc-us.vaccination.org
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mc-us.vaccination.org
      - CORE_PEER_LOCALMSPID=mc-usMSP
      - CORE_PEER_ADDRESS=peer1.mc-us.vaccination.org:7051
      # Added for CouchDB as State DB
      #- CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=peerdb.mc-us.vaccination.org:5984
    ports:
      - 11056:7051
      - 11058:7053
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/mc-us.vaccination.org/peers/peer1.mc-us.vaccination.org/:/etc/hyperledger/crypto/peer
    depends_on:
      - ca.mc-us.vaccination.org
      - peerdb.mc-us.vaccination.org
    

  # fabric-rest api server
  api.mc-us.vaccination.org:
    extends:
      file: base.yaml
      service: api-base
    container_name: api.mc-us.vaccination.org
    ports:
      - 4004:4000
    environment:
      - ORG=mc-us
      - PORT=4000
    depends_on:
      - peer0.mc-us.vaccination.org
      - peer1.mc-us.vaccination.org
    

  cli.vaccination.org:
    container_name: cli.vaccination.org
    extends:
      file: base.yaml
      service: cli-base
    volumes:
      - ../artifacts/crypto-config/ordererOrganizations/vaccination.org/orderers/orderer.vaccination.org/tls:/etc/hyperledger/crypto/orderer/tls

  cli.mc-us.vaccination.org:
    container_name: cli.mc-us.vaccination.org
    extends:
      service: cli.vaccination.org
    environment:
      - CORE_PEER_LOCALMSPID=mc-usMSP
    volumes:
        - ../artifacts/crypto-config/peerOrganizations/mc-us.vaccination.org/users/Admin@mc-us.vaccination.org:/etc/hyperledger/crypto/peer
    

  # simple http server to disseminate certificates
  www.mc-us.vaccination.org:
    extends:
      file: base.yaml
      service: www-base
    container_name: www.mc-us.vaccination.org
    ports:
      - 8085:80
